sonar.projectKey=creiddom_php-project-57
sonar.organization=creiddom

sonar.sources=app/
sonar.tests=tests/
sonar.test.inclusions=tests/**/*.php
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**

sonar.php.coverage.reportPaths=build/logs/clover.xml
